version: '3.9'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: experts_db
    ports:
      - "3310:3306"
