// http://localhost:3000/api/v1/origenes
// separador entre request: ###
POST http://localhost:3000/api/v1/origenes 
Content-Type: application/json
    
{
    "codigo_origen": "GYE",
    "nombre": "GUAYAQUIL",
    "aeropuerto": "JOSE JOAQUIN DE OLMEDO",
    "id_pais": 58,
    "id_aduana": 1
}